language: python
jobs:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.9
      env: TOXENV=py39
addons:
  postgresql: 13
branches:
  only:
    - master
cache:
  directories:
    - .tox
before_install:
 - tar -xaf ../../liberapay-liberapay.com.tar.gz --strip-components=1
install:
 - if [ "${TRAVIS_BRANCH}" = "master" -a "${TRAVIS_PULL_REQUEST}" = "false" ]; then rm -rf .tox; fi
 - pip install tox "six>=1.14.0"
before_script:
 - psql -U postgres -c 'CREATE DATABASE liberapay_tests;'
 - DATABASE_URL=liberapay_tests ./recreate-schema.sh test
 - if [ "${TRAVIS_BRANCH}" = "master" -a "${TRAVIS_PULL_REQUEST}" = "false" ]; then rm -rfv tests/py/fixtures; export LIBERAPAY_I18N_TEST=yes; fi
script: tox
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6fb3a92e8bd62a44b901
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
dist: focal
git:
  strategy: tarball
