language: python
addons:
  postgresql: 9.3
branches:
  only:
    - master
before_install:
 - node --version
cache:
  directories:
    - env/bin
    - env/lib/python2.7/site-packages
install:
 - if [ "${TRAVIS_BRANCH}" = "master" -a "${TRAVIS_PULL_REQUEST}" = "false" ]; then rm -rf env; fi
 - touch requirements.txt package.json
 - make env
 - make node_modules
 - pip install coveralls --disable-pip-version-check
before_script:
 - echo "DATABASE_URL=dbname=gratipay" | tee -a tests/local.env local.env
 - psql -U postgres -c 'CREATE DATABASE "gratipay";'
 - if [ "${TRAVIS_BRANCH}" = "master" -a "${TRAVIS_PULL_REQUEST}" = "false" ]; then rm -rfv tests/py/fixtures; fi
script: make test
after_success:
  coveralls
notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#gratipay"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"
    skip_join: true
sudo: false
