name: CI
on:
  # Trigger the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allow running this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install PostgreSQL 16
        run: |
          sudo sh -c 'echo "deb https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install -y postgresql-16
      - name: Start PostgreSQL
        run: |
          sudo systemctl cat postgresql@.service
          sudo systemctl start postgresql@16-main.service
          sudo systemctl status postgresql@16-main.service
          ls -la /var/run/postgresql/
      - name: Set libpq environment variables
        run: echo PGPORT=5432 >>$GITHUB_ENV
      - name: Create the database user
        run: sudo -E -u postgres createuser --superuser $(whoami)
      - name: Create the test database
        run: createdb liberapay_tests
      - name: Create the test database schema
        run: DATABASE_URL=liberapay_tests ./recreate-schema.sh test
      - name: Install Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Cache the .tox directory to speed things up
        uses: actions/cache@v3
        with:
          path: .tox
          key: test-${{ runner.os }}-${{ hashFiles('requirements_*.txt') }}
      - name: Enable expensive tests, on the master branch only
        if: ${{ env.GITHUB_HEAD_REF == 'master' }}
        run: |
          echo LIBERAPAY_I18N_TEST=yes >> $GITHUB_ENV
          echo VCR=off >> $GITHUB_ENV
      - name: Install tox
        run: pip install tox
      - name: Write liberapay environment file for tests
        run: |
          cat >tests/local.env <<EOF
          DATABASE_URL="port=5432 dbname=liberapay_tests"
          # As of March 2025, GitHub Actions runners still don't have IPv6,
          # so we override the default IPv6-only test email address here.
          TEST_EMAIL_ADDRESS=test@changaco.net
          EOF
      - name: Run the tests
        run: tox
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
